### PR TITLE
Update selector.inc

### PR DESCRIPTION
**Pull request by Lcfvs**
See https://github.com/Lcfvs/PHPDOM ;)

### CODE REVIEW

**Comment by Darhazer** [comment]
Other than the style changes, it seems that the :scope is the only addition. Is that correct? Can you add test for this?

**Comment by Lcfvs** [comment]
Just sent some fixes...

To answer your question, I have made ​​some changes to allow for any valid CSS identifiers, the :scope selector and the CSS4 $ selector (parent).

Unfortunately, with your code, I can't make a test code for :scope.

If you want, look to my PHPDOM to find a solution (https://github.com/Lcfvs/PHPDOM/blob/master/demo.php#L43) ;)

**Comment by Darhazer** [comment]
I looked more carefully at the code and now I see the scope of the changes :)

You know you can update the existing PR, don't you? Anyway, I'll just accept the other PR. Thank you for your contribution!

**Comment by Lcfvs** [comment]
With pleasure, thanks to you for this component. :)

**Pull request closed without merging**
